name: Full ZHILA Analysis

on: [push]

jobs:
  zhila:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: zhila
        uses: tuning003/zhila@main
        with:
          service: ${{ secrets.SERVICE }}
          check_code: ${{ secrets.CHECK_CODE }}
          language: cpp,python
          fail_on_warnings: true
